
GET http://localhost:4000/
###


GET http://localhost:4000/users
###


GET http://localhost:4000/user/ibax8@ycombinator.com
###


POST http://localhost:4000/login
Content-Type: application/json

{
    "email":"ccarrattd@trellian.com",
    "Password":"uZacSZf"
}
